name: common
description: "A new Flutter project."
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  app:
    path: ../app
  home:
    path: ../home
  order:
    path: ../order
  personal:
    path: ../personal
  provider: ^6.1.2
  fluro: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: Basteleur
      fonts:
        - asset: assets/fonts/Basteleur.ttf


